baseURL = "https://javiercaram.github.io/cuatro/"
languageCode = "es-es"
title = "Mi Repositorio Cuatro"
theme = "PaperMod"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
disableScrollToTop = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # Para bÃºsqueda

[minify]
  disableXML = true
  disableHTML = true

[params]
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionPage = true
  disableSpecial1stPost = false
  disableAnchoredHeadings = false
  disableHeadingEmoji = false
  hideSummary = false
  disableHugoGeneratorInject = false

[params.homeInfoParams]
  Title = "Â¡Hola! ðŸ‘‹"
  Content = "Bienvenido a mi sitio de Hugo. Empieza a escribir tus posts aquÃ­."